### ISSUE TITLE
macOS Monterey 12.1: Could not find the libc shared library

### ISSUE THREAD

**Issue by BlackFoundry** [fonttools/ttfautohint-py#13] opened 2022-01-31 14:35 UTC
```
File "venv/lib/python3.8/site-packages/ttfautohint/memory.py", line 18, in <module>
    raise OSError("Could not find the libc shared library")
OSError: Could not find the libc shared library
```

**Comment by anthrotype** [comment] 2022-01-31 14:38
What python3 --version exactly?
How did you install python (where from)?

**Comment by justvanrossum** [comment] 2022-01-31 14:39
Looks like this is https://bugs.python.org/issue44689

**Comment by anthrotype** [comment] 2022-01-31 14:39
Duplicate of https://github.com/fonttools/ttfautohint-py/issues/6?

**Comment by justvanrossum** [comment] 2022-01-31 14:39
So, an upgrade of Python may help.

**Comment by BlackFoundry** [comment] 2022-01-31 15:12
no issue when using Python3.10, thanks !

**Closed as completed** 2022-01-31 15:12 UTC
